### PR TITLE
Add tpmusielak as maintainer

### PR DESCRIPTION
**Pull request by tpmusielak**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tpmusielak** [comment]
@conda-forge-admin, please rerender

**Comment by tpmusielak** [comment]
Since https://github.com/conda-forge/tabula-py-feedstock/pull/14 has not been actioned for 14 days, happy to contribute as maintainer to keep the feedstock alive

**Comment by tpmusielak** [comment]
@conda-forge/core please merge - the feedstock seems to be abandoned

**Comment by tpmusielak** [comment]
@conda-forge-admin, please ping conda-forge/core

**Comment by ocefpaf** [comment]
We usually give the maintainers a week or so for them to respond.

**Comment by CurtLH** [comment]
Hi @tpmusielak -- I just merged #14, but if you're still interested in being a maintainer, we would be grateful to have you.

**Comment by tpmusielak** [comment]
Thank you @CurtLH, happy to help.

**Comment by CurtLH** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
